services:
  cvmfs:
    image: gmazzitelli/cvmfs-client
    container_name: cvmfs-client
    privileged: true
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    volumes:
      - /cvmfs:/cvmfs:shared
    environment:
      - REPO_LIST=sft.cern.ch datacloud.infn.it sft-cygno.infn.it
    restart: unless-stopped
    logging:
      driver: local
      options:
        max-size: "100m"
        max-file: "5"
